/**
 * MCP Forge 模板库 — 3 种模板管理
 *
 * 契约: contract:mcp-forge-templates v1 §2
 *
 * 模板类型:
 *   - python-fastmcp-stdio: Python FastMCP stdio server
 *   - nodejs-stdio: Node.js @modelcontextprotocol/sdk stdio server
 *   - http-api-wrapper: Node.js HTTP API wrapper (streamable-http)
 */

import type { TemplateMetadata, TemplateId, TemplatePlaceholder } from './types.js';
import { ForgeError } from './errors.js';

// ── 占位符定义 ─────────────────────────────────────────────────────────────

const PLACEHOLDERS_PYTHON: TemplatePlaceholder[] = [
  { name: 'SERVER_NAME', required: true, pattern: '^[a-zA-Z][a-zA-Z0-9_-]{0,99}$', description: 'MCP server 显示名' },
  { name: 'SERVER_ID', required: true, pattern: '^[a-z][a-z0-9_]{1,79}$', description: 'server id' },
  { name: 'TOOL_NAME', required: false, defaultValue: 'hello', pattern: '^[a-z][a-z0-9_]{0,49}$', description: '示例 tool 名称' },
  { name: 'TOOL_DESCRIPTION', required: false, defaultValue: 'Say hello', maxLength: 500, description: '示例 tool 描述' },
  { name: 'AUTHOR', required: false, defaultValue: 'Anonymous', maxLength: 100, description: '作者名' },
];

const PLACEHOLDERS_NODEJS: TemplatePlaceholder[] = [
  { name: 'SERVER_NAME', required: true, pattern: '^[a-zA-Z][a-zA-Z0-9_-]{0,99}$', description: 'MCP server 显示名' },
  { name: 'SERVER_ID', required: true, pattern: '^[a-z][a-z0-9_]{1,79}$', description: 'server id' },
  { name: 'TOOL_NAME', required: false, defaultValue: 'hello', pattern: '^[a-z][a-z0-9_]{0,49}$', description: '示例 tool 名称' },
  { name: 'TOOL_DESCRIPTION', required: false, defaultValue: 'Say hello', maxLength: 500, description: '示例 tool 描述' },
  { name: 'AUTHOR', required: false, defaultValue: 'Anonymous', maxLength: 100, description: '作者名' },
];

const PLACEHOLDERS_HTTP: TemplatePlaceholder[] = [
  { name: 'SERVER_NAME', required: true, pattern: '^[a-zA-Z][a-zA-Z0-9_-]{0,99}$', description: 'MCP server 显示名' },
  { name: 'SERVER_ID', required: true, pattern: '^[a-z][a-z0-9_]{1,79}$', description: 'server id' },
  { name: 'UPSTREAM_API_URL', required: true, pattern: '^https?://.+', description: '被包装的上游 API URL' },
  { name: 'UPSTREAM_API_KEY', required: false, description: '上游 API key（写入 .env，不硬编码）' },
  { name: 'PORT', required: false, defaultValue: '3000', pattern: '^\\d{2,5}$', description: 'HTTP 监听端口' },
  { name: 'AUTHOR', required: false, defaultValue: 'Anonymous', maxLength: 100, description: '作者名' },
];

// ── Python FastMCP stdio 骨架 ──────────────────────────────────────────────

const PYTHON_SERVER_PY = `"""
{{SERVER_NAME}} — MCP Server (Python FastMCP stdio)

Generated by Lingxiao MCP Forge.
Author: {{AUTHOR}}
"""
from fastmcp import FastMCP

# Create the MCP server instance
mcp = FastMCP("{{SERVER_NAME}}")


@mcp.tool
def {{TOOL_NAME}}() -> str:
    """{{TOOL_DESCRIPTION}}"""
    return "Hello from {{SERVER_NAME}}!"


if __name__ == "__main__":
    mcp.run()
`;

const PYTHON_REQUIREMENTS = `fastmcp>=2.0.0
`;

const PYTHON_README = `# {{SERVER_NAME}}

MCP Server generated by Lingxiao MCP Forge.

## Installation

\`\`\`bash
pip install -r requirements.txt
\`\`\`

## Run

\`\`\`bash
python server.py
\`\`\`

## Register to Lingxiao

The server is auto-registered. To manually register:

\`\`\`
/mcp add-stdio {{SERVER_ID}} python3 server.py
\`\`\`
`;

// ── Node.js stdio 骨架 ─────────────────────────────────────────────────────

const NODEJS_INDEX_TS = `/**
 * {{SERVER_NAME}} — MCP Server (Node.js stdio)
 *
 * Generated by Lingxiao MCP Forge.
 * Author: {{AUTHOR}}
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const server = new McpServer({
  name: "{{SERVER_NAME}}",
  version: "1.0.0",
});

server.tool(
  "{{TOOL_NAME}}",
  "{{TOOL_DESCRIPTION}}",
  {},
  async () => ({
    content: [{ type: "text" as const, text: "Hello from {{SERVER_NAME}}!" }],
  }),
);

// Start the server with stdio transport
const transport = new StdioServerTransport();
await server.connect(transport);
`;

const NODEJS_PACKAGE_JSON = `{
  "name": "{{SERVER_ID}}",
  "version": "1.0.0",
  "description": "{{SERVER_NAME}} — MCP Server generated by Lingxiao MCP Forge",
  "type": "module",
  "scripts": {
    "start": "node index.js",
    "build": "tsc"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "zod": "^3.23.0"
  }
}
`;

const NODEJS_README = `# {{SERVER_NAME}}

MCP Server generated by Lingxiao MCP Forge.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm start
\`\`\`

## Register to Lingxiao

\`\`\`
/mcp add-stdio {{SERVER_ID}} node index.js
\`\`\`
`;

// ── HTTP API wrapper 骨架 ──────────────────────────────────────────────────

const HTTP_INDEX_TS = `/**
 * {{SERVER_NAME}} — MCP Server (HTTP API Wrapper, streamable-http)
 *
 * Generated by Lingxiao MCP Forge.
 * Author: {{AUTHOR}}
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";
import http from "http";

const PORT = parseInt(process.env.PORT || "{{PORT}}", 10);
const UPSTREAM_API_URL = process.env.UPSTREAM_API_URL || "{{UPSTREAM_API_URL}}";
const UPSTREAM_API_KEY = process.env.UPSTREAM_API_KEY || "";

const server = new McpServer({
  name: "{{SERVER_NAME}}",
  version: "1.0.0",
});

// Example tool: proxy a request to the upstream API
server.tool(
  "fetch_upstream",
  "Fetch data from the upstream API",
  { path: z.string().describe("API path to fetch") },
  async ({ path }) => {
    try {
      const url = \`\${UPSTREAM_API_URL}\${path}\`;
      const headers: Record<string, string> = {};
      if (UPSTREAM_API_KEY) {
        headers["Authorization"] = \`Bearer \${UPSTREAM_API_KEY}\`;
      }
      const resp = await fetch(url, { headers });
      const data = await resp.text();
      return {
        content: [{ type: "text" as const, text: data }],
        isError: !resp.ok,
      };
    } catch (err) {
      return {
        content: [{ type: "text" as const, text: String(err) }],
        isError: true,
      };
    }
  },
);

// Start streamable-http transport
const httpServer = http.createServer(async (req, res) => {
  if (req.url === "/mcp") {
    const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
    await server.connect(transport);
    await transport.handleRequest(req, res);
  } else {
    res.writeHead(404).end("Not found");
  }
});

httpServer.listen(PORT, () => {
  console.log("{{SERVER_NAME}} MCP server listening on port " + PORT);
});
`;

const HTTP_PACKAGE_JSON = `{
  "name": "{{SERVER_ID}}",
  "version": "1.0.0",
  "description": "{{SERVER_NAME}} — MCP HTTP API Wrapper generated by Lingxiao MCP Forge",
  "type": "module",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "zod": "^3.23.0"
  }
}
`;

const HTTP_ENV_EXAMPLE = `PORT={{PORT}}
UPSTREAM_API_URL={{UPSTREAM_API_URL}}
UPSTREAM_API_KEY=your-api-key-here
`;

const HTTP_README = `# {{SERVER_NAME}}

MCP HTTP API Wrapper generated by Lingxiao MCP Forge.

## Installation

\`\`\`bash
npm install
\`\`\`

## Configuration

Copy \`.env.example\` to \`.env\` and configure:

\`\`\`bash
cp .env.example .env
\`\`\`

## Run

\`\`\`bash
npm start
\`\`\`

The server will be available at \`http://localhost:{{PORT}}/mcp\`.

## Register to Lingxiao

\`\`\`
/mcp add-remote {{SERVER_ID}} http://localhost:{{PORT}}/mcp {{SERVER_NAME}}
\`\`\`
`;

// ── 模板元数据 ─────────────────────────────────────────────────────────────

const TEMPLATES: Record<TemplateId, TemplateMetadata> = {
  'python-fastmcp-stdio': {
    id: 'python-fastmcp-stdio',
    name: 'Python FastMCP (stdio)',
    language: 'python',
    transport: 'stdio',
    framework: 'FastMCP (fastmcp>=2.0)',
    description: 'Python MCP server using FastMCP framework with stdio transport. Best for quick Python-based tool servers.',
    placeholders: PLACEHOLDERS_PYTHON,
    files: [
      { path: 'server.py', content: PYTHON_SERVER_PY },
      { path: 'requirements.txt', content: PYTHON_REQUIREMENTS },
      { path: 'README.md', content: PYTHON_README },
    ],
    entryPoint: 'server.py',
    registrationConfig: {
      command: 'python3',
      args: ['server.py'],
    },
  },
  'nodejs-stdio': {
    id: 'nodejs-stdio',
    name: 'Node.js (stdio)',
    language: 'typescript',
    transport: 'stdio',
    framework: '@modelcontextprotocol/sdk',
    description: 'Node.js MCP server using official SDK with stdio transport. Best for JavaScript/TypeScript tool servers.',
    placeholders: PLACEHOLDERS_NODEJS,
    files: [
      { path: 'index.js', content: NODEJS_INDEX_TS },
      { path: 'package.json', content: NODEJS_PACKAGE_JSON },
      { path: 'README.md', content: NODEJS_README },
    ],
    entryPoint: 'index.js',
    registrationConfig: {
      command: 'node',
      args: ['index.js'],
    },
  },
  'http-api-wrapper': {
    id: 'http-api-wrapper',
    name: 'HTTP API Wrapper (streamable-http)',
    language: 'typescript',
    transport: 'streamable-http',
    framework: '@modelcontextprotocol/sdk + http',
    description: 'Node.js MCP server that wraps an upstream HTTP API, exposing it via streamable-http transport. Best for proxying existing REST APIs as MCP tools.',
    placeholders: PLACEHOLDERS_HTTP,
    files: [
      { path: 'index.js', content: HTTP_INDEX_TS },
      { path: 'package.json', content: HTTP_PACKAGE_JSON },
      { path: '.env.example', content: HTTP_ENV_EXAMPLE },
      { path: 'README.md', content: HTTP_README },
    ],
    entryPoint: 'index.js',
    registrationConfig: {
      urlPattern: 'http://localhost:{{PORT}}/mcp',
    },
  },
};

// ── 模板库 API ─────────────────────────────────────────────────────────────

export class TemplateLibrary {
  /** 列出所有模板 */
  static listTemplates(): TemplateMetadata[] {
    return Object.values(TEMPLATES);
  }

  /** 获取指定模板 */
  static getTemplate(id: TemplateId): TemplateMetadata {
    const template = TEMPLATES[id];
    if (!template) {
      throw new ForgeError(
        'FORGE_TEMPLATE_NOT_FOUND',
        `Unknown template ID: ${id}`,
        { retryable: false },
      );
    }
    return template;
  }

  /** 根据语言/传输方式推荐模板 */
  static recommendTemplate(
    language?: 'python' | 'typescript',
    transport?: 'stdio' | 'streamable-http',
  ): TemplateId {
    if (transport === 'streamable-http') return 'http-api-wrapper';
    if (language === 'python') return 'python-fastmcp-stdio';
    return 'nodejs-stdio';
  }

  /**
   * 验证占位符值，返回填充后的值映射。
   * 必填占位符缺失时抛出 FORGE_INVALID_REQUEST。
   */
  static resolvePlaceholders(
    templateId: TemplateId,
    values: Record<string, string>,
  ): Record<string, string> {
    const template = TemplateLibrary.getTemplate(templateId);
    const resolved: Record<string, string> = {};

    for (const ph of template.placeholders) {
      const value = values[ph.name] ?? ph.defaultValue;

      if (ph.required && !value) {
        throw new ForgeError(
          'FORGE_INVALID_REQUEST',
          `Missing required placeholder: ${ph.name}`,
          { detail: `Placeholder '${ph.name}' is required for template '${templateId}'`, retryable: false },
        );
      }

      if (!value) continue;

      // Pattern validation
      if (ph.pattern) {
        const regex = new RegExp(ph.pattern);
        if (!regex.test(value)) {
          throw new ForgeError(
            'FORGE_INVALID_REQUEST',
            `Invalid value for placeholder ${ph.name}: '${value}' does not match pattern ${ph.pattern}`,
            { retryable: false },
          );
        }
      }

      // maxLength validation
      if (ph.maxLength && value.length > ph.maxLength) {
        throw new ForgeError(
          'FORGE_INVALID_REQUEST',
          `Placeholder ${ph.name} value exceeds maxLength ${ph.maxLength}`,
          { retryable: false },
        );
      }

      resolved[ph.name] = value;
    }

    return resolved;
  }

  /**
   * 将模板文件中的占位符替换为实际值，返回填充后的文件列表。
   */
  static renderTemplate(
    templateId: TemplateId,
    values: Record<string, string>,
  ): { files: Array<{ path: string; content: string }>; entryPoint: string } {
    const template = TemplateLibrary.getTemplate(templateId);
    const resolved = TemplateLibrary.resolvePlaceholders(templateId, values);

    const renderedFiles = template.files.map((file) => {
      let content = file.content;
      for (const [key, val] of Object.entries(resolved)) {
        content = content.replaceAll(`{{${key}}}`, val);
      }
      // Also replace in file path
      let filePath = file.path;
      for (const [key, val] of Object.entries(resolved)) {
        filePath = filePath.replaceAll(`{{${key}}}`, val);
      }
      return { path: filePath, content };
    });

    return { files: renderedFiles, entryPoint: template.entryPoint };
  }
}
